export const africaToCurrency: Record<string, string> = {
  "Algeria": "ngn",
  "Angola": "ngn",
  "Benin": "ngn",
  "Botswana": "ngn",
  "Burkina_Faso": "ngn",
  "Burundi": "ngn",
  "Cabo Verde": "ngn",
  "Cameroon": "ngn",
  "Central African Republic": "ngn",
  "Chad": "ngn",
  "Comoros": "ngn",
  "Congo": "ngn",
  "Democratic Republic of the Congo": "ngn",
  "Djibouti": "ngn",
  "Egypt": "ngn",
  "Equatorial Guinea": "ngn",
  "Eritrea": "ngn",
  "Eswatini": "ngn",
  "Ethiopia": "ngn",
  "Gabon": "ngn",
  "Gambia": "ngn",
  "Ghana": "ngn",
  "Guinea": "ngn",
  "Guinea-Bissau": "ngn",
  "Ivory Coast": "ngn",
  "Kenya": "ngn",
  "Lesotho": "ngn",
  "Liberia": "ngn",
  "Libya": "ngn",
  "Madagascar": "ngn",
  "Malawi": "ngn",
  "Mali": "ngn",
  "Mauritania": "ngn",
  "Mauritius": "ngn",
  "Morocco": "ngn",
  "Mozambique": "ngn",
  "Namibia": "ngn",
  "Niger": "ngn",
  "Nigeria": "ngn",
  "Rwanda": "ngn",
  "Sao Tome and Principe": "ngn",
  "Senegal": "ngn",
  "Seychelles": "ngn",
  "Sierra Leone": "ngn",
  "Somalia": "ngn",
  "South Africa": "ngn",
  "South Sudan": "ngn",
  "Sudan": "ngn",
  "Tanzania": "ngn",
  "Togo": "ngn",
  "Tunisia": "ngn",
  "Uganda": "ngn",
  "Zambia": "ngn",
  "Zimbabwe": "ngn"
};
