export const filterField: string[] = [
  "searchTerm",
  "hotelName",
  "hotelRoomType",
  "hotelBusinessType",
  "hotelCity",
  "hotelCountry",
  "hotelRating",
  "category",
  "hotelNumberOfRooms",
  "hotelNumAdults",
  "hotelNumChildren",
  "minPrice",
  "maxPrice",
  "fromDate",
  "toDate",
  "hotelBreakfast",
  "hotelAccommodationType",
  "hotelKitchen",
  "hoitelWifi",
  "hotelParking",
  "hotelRestaurant",
  "hotelGym",
  "hotelPool",
  "hotelSpa",
  "hotel24HourFrontDesk",
  "hotelAirportShuttle",
  "hotelNoSmokingPreference",
  "hotelNoNSmoking",
  "hotelSmoking",
  "hotelNoPetsPreferences",
  "hotelPetsAllowed",
  "hotelPetsNotAllowed",
  "hotelLocationFeatureWaterView",
  "hotelLocationFeatureIsland",

  "hotelAC",
  "hotelTv",
  "hotelWashing",
  "hotelCoffeeBar",
];

export const searchableFields: string[] = [
  "hotelName",
  "hotelCity",
  "hotelCountry",
];

export const numericFields = [
  "hotelNumberOfRooms",
  "hotelNumAdults",
  "hotelNumChildren",
  "hotelRoomPriceNight",
];

export const searchableFieldsHotel = [
  "hotelBusinessName",
  "hotelName",
  "hotelBusinessType",
  "hotelPhone",
  "hotelEmail",
  "businessTagline",
  "businessDescription",
  "hotelBookingCondition",
  "hotelCancelationPolicy",
];
