export type IHotelFilterRequest = {
  searchTerm?: string | undefined;
  hotelName?: string | undefined;
  hotelRoomType?: string | undefined;
  hotelRating?: string | undefined;
  hotelCity?: string | undefined;
  hotelCountry?: string | undefined;
  category?: string | undefined;
  minPrice?: number | undefined;
  maxPrice?: number | undefined;
  fromDate?: string | undefined;
  toDate?: string | undefined;
  hotelBreakfast?: boolean | undefined;
  hotelKitchen?: boolean | undefined;
  hoitelWifi?: boolean | undefined;
  hotelParking?: boolean | undefined;
  hotelRestaurant?: boolean | undefined;
  hotelGym?: boolean | undefined;
  hotelPool?: boolean | undefined;
  hotelSpa?: boolean | undefined;
  hotel24HourFrontDesk?: boolean | undefined;
  hotelAirportShuttle?: boolean | undefined;
  hotelNoSmokingPreference?: boolean | undefined;
  hotelNonSmokingRooms?: boolean | undefined;
  hotelSmoking?: boolean | undefined;
  hotelNoPetsPreferences?: boolean | undefined;
  hotelPetsAllowed?: boolean | undefined;
  hotelPetsNotAllowed?: boolean | undefined;
  hotelLocationFeatureWaterView?: boolean | undefined;
  hotelLocationFeatureIsland?: boolean | undefined;

  hotelAC?: boolean | undefined;
  hotelTv?: boolean | undefined;
  hotelWashing?: boolean | undefined;
  hotelCoffeeBar?: boolean | undefined;
};
